### ISSUE TITLE
Manuális kód átvizsgálás + Statikus analízis

### ISSUE THREAD

**Issue by SsyMa** [BME-MIT-IET/iet-hf-2023-epp-idoben#1]
A manuális kód átvizsgálást és a statikus analízist IntelliJ-ben végezzük a SonarLint plug-in segítségével. A talált hibákat ki is javítjuk majd.

**Comment by annanasz** [comment]
#7 A feladatot közösen (Vass Annamária, Kiovics Dániel) egy fizikai térben oldottuk meg Kiovics Dániel gépéről.
