### ISSUE TITLE
Build keretrendszer beüzemelése + CI beüzemelése

### ISSUE THREAD

**Issue by SsyMa** [BME-MIT-IET/iet-hf-2023-epp-idoben#3]
A build keretrendszert fogjuk beüzemelni, aminek a keretében Maven alapra konvertáljuk a projektet. Ezek után beállítjuk, hogy a GitHub felületén minden push esetén lefusson egy automatikus ellenőrzés.

**Comment by kofinandi** [comment]
#6 A feladatot közösen (Kiovics Dániel, Kőfaragó Nándor) egy fizikai térben oldottuk meg Kőfaragó Nándor gépéről.

**Comment by annanasz** [comment]
Szénássy Mártonnal megnéztük a megoldott feladatot, szerintünk rendben van!
